CREATE TABLE comment
(
    commentid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 100 ),
    author_name character varying(150)  NOT NULL,
    comment character varying(350)  NOT NULL,
    dat datetime  NOT NULL,
    authorid integer  NOT NULL,
    eventid integer  NOT NULL,
    CONSTRAINT comment_pkey PRIMARY KEY (commentid),
    CONSTRAINT comment_authorid_fkey FOREIGN KEY (authorid) REFERENCES users (userid),
    CONSTRAINT comment_eventid_fkey FOREIGN KEY (eventid) REFERENCES event(eventid)
)
