CREATE TABLE event
(
    eventid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 100 ),
    title character varying(150)  NOT NULL,
    event_description character varying(350)  NOT NULL,
    loc character varying(150)  NOT NULL,
    dat character datetime  NOT NULL,
    CONSTRAINT event_pkey PRIMARY KEY (eventid)
)
